# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 578)
        MainWindow.setStyleSheet("#side_widget QPushButton{\n"
"text-align:center;\n"
"background:transparent\n"
"}\n"
"\n"
"#chat_list_frame{\n"
"    border-top: 0.5px solid #4d4d4f;\n"
"}\n"
"\n"
"#chat_list_frame QPushButton{\n"
"    color: #fff;\n"
"    border:none;\n"
"    padding:10px;\n"
"    border-radius: 5px;\n"
"    background:none\n"
"\n"
"}\n"
"\n"
"#chat_list_frame QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#Button_iniciar{\n"
"    border: 1px solid rgb(77, 77, 79);\n"
"    color: #fff;\n"
"    border-radius:5px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"#side_widget{\n"
"    background-color: rgb(32, 33, 35);\n"
"}\n"
"\n"
"#side_widget QPushButton:hover{\n"
"    background-color: rgb(42, 43, 50);\n"
"}\n"
"\n"
"#chat_list{\n"
"    boder:none\n"
"}\n"
"\n"
"#input_frame{\n"
"    border: 1px solid #e5e5e5;\n"
"    background: #fff;\n"
"    border-radius: 5px\n"
"\n"
"}\n"
"\n"
"#input_textEdit,\n"
"#scrollArea{\n"
"    border:none\n"
"}\n"
"\n"
"#main_widget,\n"
"#scrollAreaWidgetContents{\n"
"    background: #fff;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"#escuta_frame{\n"
"    border: none;\n"
"}\n"
"\n"
"#frame_icone,\n"
"#new_chat_file,\n"
"#frame,\n"
"#menu_frame,\n"
"#frame_logoIf,\n"
"#frame_info{\n"
"    border:none\n"
"}\n"
"\n"
"#Dev_by,\n"
"#Dev_nome,\n"
"#Nome_prof,\n"
"#Orientacoes,\n"
"#Prof_orie,\n"
"#titulo\n"
"{\n"
"    color:white\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.side_widget = QtWidgets.QWidget(self.centralwidget)
        self.side_widget.setMinimumSize(QtCore.QSize(0, 500))
        self.side_widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_widget.setObjectName("side_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.new_chat_file = QtWidgets.QFrame(self.side_widget)
        self.new_chat_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_chat_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_chat_file.setObjectName("new_chat_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.new_chat_file)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_iniciar = QtWidgets.QPushButton(self.new_chat_file)
        self.Button_iniciar.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_iniciar.setFont(font)
        self.Button_iniciar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_iniciar.setFlat(False)
        self.Button_iniciar.setObjectName("Button_iniciar")
        self.verticalLayout_2.addWidget(self.Button_iniciar)
        self.verticalLayout_3.addWidget(self.new_chat_file)
        self.menu_frame = QtWidgets.QFrame(self.side_widget)
        self.menu_frame.setMinimumSize(QtCore.QSize(200, 400))
        self.menu_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_logoIf = QtWidgets.QFrame(self.menu_frame)
        self.frame_logoIf.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_logoIf.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_logoIf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logoIf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logoIf.setObjectName("frame_logoIf")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_logoIf)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.frame_logoIf)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icones/logo_ifba.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_logoIf)
        self.frame_info = QtWidgets.QFrame(self.menu_frame)
        self.frame_info.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_info)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.titulo = QtWidgets.QLabel(self.frame_info)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titulo.setScaledContents(False)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setWordWrap(True)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_6.addWidget(self.titulo)
        self.Dev_by = QtWidgets.QLabel(self.frame_info)
        self.Dev_by.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Dev_by.setFont(font)
        self.Dev_by.setObjectName("Dev_by")
        self.verticalLayout_6.addWidget(self.Dev_by)
        self.Dev_nome = QtWidgets.QLabel(self.frame_info)
        self.Dev_nome.setObjectName("Dev_nome")
        self.verticalLayout_6.addWidget(self.Dev_nome)
        self.Prof_orie = QtWidgets.QLabel(self.frame_info)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Prof_orie.setFont(font)
        self.Prof_orie.setObjectName("Prof_orie")
        self.verticalLayout_6.addWidget(self.Prof_orie)
        self.Nome_prof = QtWidgets.QLabel(self.frame_info)
        self.Nome_prof.setObjectName("Nome_prof")
        self.verticalLayout_6.addWidget(self.Nome_prof)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.Orientacoes = QtWidgets.QLabel(self.frame_info)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Orientacoes.setFont(font)
        self.Orientacoes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Orientacoes.setScaledContents(False)
        self.Orientacoes.setAlignment(QtCore.Qt.AlignCenter)
        self.Orientacoes.setWordWrap(True)
        self.Orientacoes.setObjectName("Orientacoes")
        self.verticalLayout_6.addWidget(self.Orientacoes)
        self.verticalLayout_4.addWidget(self.frame_info)
        self.verticalLayout_3.addWidget(self.menu_frame)
        self.chat_list_frame = QtWidgets.QFrame(self.side_widget)
        self.chat_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_list_frame.setObjectName("chat_list_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.chat_list_frame)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.chat_list_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_sair = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_sair.setFont(font)
        self.Button_sair.setObjectName("Button_sair")
        self.horizontalLayout.addWidget(self.Button_sair)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_3.addWidget(self.chat_list_frame)
        self.gridLayout.addWidget(self.side_widget, 0, 0, 1, 1)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.input_frame = QtWidgets.QFrame(self.main_widget)
        self.input_frame.setMinimumSize(QtCore.QSize(50, 0))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_textEdit = QtWidgets.QTextEdit(self.input_frame)
        self.input_textEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.input_textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.input_textEdit.setObjectName("input_textEdit")
        self.gridLayout_2.addWidget(self.input_textEdit, 0, 1, 2, 1)
        self.Button_enviar = QtWidgets.QPushButton(self.input_frame)
        self.Button_enviar.setObjectName("Button_enviar")
        self.gridLayout_2.addWidget(self.Button_enviar, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.input_frame, 1, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 625, 416))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 3, 1, 1)
        self.escuta_frame = QtWidgets.QFrame(self.main_widget)
        self.escuta_frame.setMinimumSize(QtCore.QSize(500, 0))
        self.escuta_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.escuta_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.escuta_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.escuta_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.escuta_frame.setObjectName("escuta_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.escuta_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_icone = QtWidgets.QFrame(self.escuta_frame)
        self.frame_icone.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icone.setObjectName("frame_icone")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_icone)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.icon_Habilitar_voz = QtWidgets.QLabel(self.frame_icone)
        self.icon_Habilitar_voz.setMaximumSize(QtCore.QSize(50, 50))
        self.icon_Habilitar_voz.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.icon_Habilitar_voz.setText("")
        self.icon_Habilitar_voz.setPixmap(QtGui.QPixmap(":/icones/icone_audio.png"))
        self.icon_Habilitar_voz.setScaledContents(True)
        self.icon_Habilitar_voz.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_Habilitar_voz.setObjectName("icon_Habilitar_voz")
        self.horizontalLayout_2.addWidget(self.icon_Habilitar_voz)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_5.addWidget(self.frame_icone)
        self.Habilitar_voz = QtWidgets.QLabel(self.escuta_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Habilitar_voz.setFont(font)
        self.Habilitar_voz.setAlignment(QtCore.Qt.AlignCenter)
        self.Habilitar_voz.setObjectName("Habilitar_voz")
        self.verticalLayout_5.addWidget(self.Habilitar_voz)
        self.gridLayout_3.addWidget(self.escuta_frame, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.main_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_iniciar.setText(_translate("MainWindow", "Iniciar Assistente"))
        self.titulo.setText(_translate("MainWindow", "Assistente Virtual em Python"))
        self.Dev_by.setText(_translate("MainWindow", "Desenvolvido Por:"))
        self.Dev_nome.setText(_translate("MainWindow", "Luis Filipe Vieira Silva"))
        self.Prof_orie.setText(_translate("MainWindow", "Professor Orientador:"))
        self.Nome_prof.setText(_translate("MainWindow", "Luis Paulo"))
        self.Orientacoes.setText(_translate("MainWindow", "Inicie o programa apertando o botao iniciar assistente a aguarde o programa autorizar a entrada de audio"))
        self.Button_sair.setText(_translate("MainWindow", "Fechar o programa"))
        self.Button_enviar.setText(_translate("MainWindow", "Enviar"))
        self.Habilitar_voz.setText(_translate("MainWindow", "Aguardando solicitaçao: Fale agora"))
from assets import icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
