# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 578)
        MainWindow.setStyleSheet("#side_widget QPushButton{\n"
"text-align:left;\n"
"background:transparent\n"
"}\n"
"\n"
"#chat_list_frame{\n"
"    border-top: 0.5px solid #4d4d4f;\n"
"}\n"
"\n"
"#chat_list_frame QPushButton{\n"
"    color: #fff;\n"
"    border:none;\n"
"    padding:10px;\n"
"    border-radius: 5px;\n"
"    background:none\n"
"\n"
"}\n"
"\n"
"#chat_list_frame QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#Button_iniciar{\n"
"    border: 1px solid rgb(77, 77, 79);\n"
"    color: #fff;\n"
"    border-radius:5px;\n"
"    padding: 10px\n"
"\n"
"}\n"
"\n"
"#side_widget{\n"
"    background-color: rgb(32, 33, 35);\n"
"}\n"
"\n"
"#side_widget QPushButton:hover{\n"
"    background-color: rgb(42, 43, 50);\n"
"}\n"
"\n"
"#chat_list{\n"
"    boder:none\n"
"}\n"
"\n"
"#input_frame{\n"
"    border: 1px solid #e5e5e5;\n"
"    background: #fff;\n"
"    border-radius: 5px\n"
"\n"
"}\n"
"\n"
"#input_textEdit,\n"
"#scrollArea{\n"
"    border:none\n"
"}\n"
"\n"
"#main_widget,\n"
"#scrollAreaWidgetContents{\n"
"    background: #fff;\n"
"    margin: 0px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.side_widget = QtWidgets.QWidget(self.centralwidget)
        self.side_widget.setMinimumSize(QtCore.QSize(0, 500))
        self.side_widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_widget.setObjectName("side_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.new_chat_file = QtWidgets.QFrame(self.side_widget)
        self.new_chat_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_chat_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_chat_file.setObjectName("new_chat_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.new_chat_file)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_iniciar = QtWidgets.QPushButton(self.new_chat_file)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_iniciar.setFont(font)
        self.Button_iniciar.setObjectName("Button_iniciar")
        self.verticalLayout_2.addWidget(self.Button_iniciar)
        self.verticalLayout_3.addWidget(self.new_chat_file)
        self.menu_frame = QtWidgets.QFrame(self.side_widget)
        self.menu_frame.setMinimumSize(QtCore.QSize(200, 500))
        self.menu_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.menu_frame)
        self.chat_list_frame = QtWidgets.QFrame(self.side_widget)
        self.chat_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_list_frame.setObjectName("chat_list_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.chat_list_frame)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.chat_list_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Button_sair = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_sair.setFont(font)
        self.Button_sair.setObjectName("Button_sair")
        self.horizontalLayout.addWidget(self.Button_sair)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_3.addWidget(self.chat_list_frame)
        self.gridLayout.addWidget(self.side_widget, 0, 0, 1, 1)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 645, 415))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(0)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.input_frame = QtWidgets.QFrame(self.main_widget)
        self.input_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_textEdit = QtWidgets.QTextEdit(self.input_frame)
        self.input_textEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.input_textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.input_textEdit.setObjectName("input_textEdit")
        self.gridLayout_2.addWidget(self.input_textEdit, 0, 0, 2, 1)
        self.Button_enviar = QtWidgets.QPushButton(self.input_frame)
        self.Button_enviar.setObjectName("Button_enviar")
        self.gridLayout_2.addWidget(self.Button_enviar, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.input_frame, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.main_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_iniciar.setText(_translate("MainWindow", "Iniciar"))
        self.label.setText(_translate("MainWindow", "LOGOUT"))
        self.Button_sair.setText(_translate("MainWindow", "Fechar o programa"))
        self.Button_enviar.setText(_translate("MainWindow", "Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
